opentelemetry-demo:
  components:
    recommendationService:
      envOverrides:
      - name: ENABLE_CACHE
        value: true
      podAnnotations:
        logzio/commit_url: somecommit
      resources:
        limits:
          memory: 1000Mi
      service:
        annotations:
          logzio/commit_url: somecommit
  default:
    envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: mycomp-monitoring-otel-collector.demo-monitoring.svc.cluster.local
  grafana:
    enabled: false
  jaeger:
    enabled: false
  opentelemetry-collector:
    enabled: false
  prometheus:
    enabled: false
