opentelemetry-demo:
  default:
    envOverrides:
      - name: OTEL_COLLECTOR_NAME
        value: logzio-monitoring-otel-collector.demo-monitoring.svc.cluster.local

  opentelemetry-collector:
    enabled: false

  jaeger:
    enabled: false

  prometheus:
    enabled: false

  grafana:
    enabled: false

  components:
    recommendationService:
      envOverrides:
        - name: ENABLE_CACHE
          value: false
      podAnnotations:
        logzio/commit_url: somecommit
      service:
        annotations:
          logzio/commit_url: somecommit
      resources:
        limits:
          memory: 1000Mi